const express = require('express')
const app = express()
app.use(express.json())
app.get('/health', (req,res)=>res.json({status:'ok', obm:'ivoire-monade'}))
app.listen(4000, ()=>console.log('API on http://localhost:4000'))
